name: zooper_flutter_ddd_domain
description: A core project for Domain Driven Design (DDD) on the domain side
version: 1.0.1
homepage: https://github.com/zooper-lib

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: